version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    allow:
      - dependency-name: 'puppeteer'
      - dependency-name: 'puppeteer-core'
      - dependency-type: 'production'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 2
