name: Pre-release

permissions: read-all

on:
  push:
    branches:
      - release-please-*

jobs:
  pre-release:
    if: "${{ startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Build docs
        run: npm run docs
      - name: Format
        run: npm run format
      - name: Commit
        run: |
          git config --global user.name 'release-please[bot]'
          git config --global user.email '55107282+release-please[bot]@users.noreply.github.com'
          git add --all
          if ! git diff-index --quiet HEAD; then
            git commit -m 'chore: generate docs'
            git push --no-verify
          fi
