name: Publish

permissions: read-all

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish @puppeteer/replay
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_REPLAY}}
        run: |
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish --access=public
